.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH qrab-install-skill 1  "install-skill 0.1.4" 
.SH NAME
qrab\-install\-skill \- Install the qrab agent skill in the current project
.SH SYNOPSIS
\fBqrab install\-skill\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Install the qrab agent skill in the current project
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.4
