//! Collects the circuits the playground offers in its example menu.
//!
//! The list is generated rather than written out so that adding a fixture to
//! `tests/qpic/` puts it in the playground automatically, and so a renamed or
//! deleted one is a build error instead of a stale menu entry.

use std::error::Error;
use std::path::{Path, PathBuf};
use std::{env, fs};

/// Circuits that introduce the language, in the order the README presents them.
///
/// `examples/imports.qrab` is deliberately absent: it resolves a relative path
/// at load time, which the browser has no filesystem to do.
const GUIDED: &[&str] = &[
    "bell",
    "teleportation",
    "functions",
    "annotations",
    "regions",
    "lifecycle",
    "programming",
    "measurements",
    "styling",
    "ellipsis",
    "escapes",
];

fn main() -> Result<(), Box<dyn Error>> {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?).join("..");
    let mut entries = Vec::new();

    for name in GUIDED {
        entries.push(entry(
            "Guide",
            name,
            &root.join(format!("examples/{name}.qrab")),
        ));
    }

    // The ported qpic corpus is the interesting half of the menu: it is what
    // proves the language covers the reference tool, so all of it ships.
    let mut ported = fs::read_dir(root.join("tests/qpic"))?
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "qrab")
        })
        .collect::<Vec<_>>();
    ported.sort();
    for path in &ported {
        let name = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .ok_or("fixture name is not UTF-8")?;
        entries.push(entry("qpic", name, path));
    }

    let generated = format!(
        "/// `(group, name, source)`, generated by `build.rs`.\n\
         pub(crate) const EXAMPLES: &[(&str, &str, &str)] = &[\n{}];\n",
        entries.join("")
    );
    fs::write(
        PathBuf::from(env::var("OUT_DIR")?).join("examples.rs"),
        generated,
    )?;

    println!("cargo::rerun-if-changed=../examples");
    println!("cargo::rerun-if-changed=../tests/qpic");
    println!("cargo::rerun-if-changed=build.rs");
    Ok(())
}

fn entry(group: &str, name: &str, path: &Path) -> String {
    format!(
        "    ({group:?}, {name:?}, include_str!({:?})),\n",
        path.display().to_string()
    )
}
